services:
    
  

    
  backend:
      build:
        context: ./Backend/server
        dockerfile: Dockerfile
      deploy:
        replicas: 10 # Define how many backend instances to spawn
      restart: always
      expose:
        - "3001"
      depends_on:
        - mongo
        - redis
      environment:
        - MONGO_URI=mongodb://mongo:27017/tradingDB
        - PORT=3001
        - REDIS_HOST=redis
        - REDIS_PORT=6379
      networks:
        - trading_network
      


  
  mongo:
    image: mongo:latest
    container_name: trading_mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - trading_network
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: trading_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - trading_network
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:latest
    container_name: trading_nginx
    restart: always
    depends_on:
      - backend
    ports:
      - "1900:1900"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - trading_network

networks:
  trading_network:

volumes:
  mongo_data:
  redis_data:
